config/routes.rb
Rails.application.routes.draw do
  get 'user_sessions/new'
  get 'user_sessions/create'
  get 'user_sessions/destroy'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "users#index"
  resources :users
  resources :localities
  resources :offices
  resources :appointments

  get 'login' => 'user_sessions#new', :as => :login
  post 'login' => "user_sessions#create"
  post 'logout' => 'user_sessions#destroy', :as => :logout
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/appointment.rb
class Appointment < ApplicationRecord
    validates :datetime, presence: true
    validates :motive, presence: true
    belongs_to :client
    belongs_to :employee
    belongs_to :office
end

app/models/locality.rb
class Locality < ApplicationRecord
    validates :name, presence: true
    validates :province, presence: true
    validates :name, uniqueness: {scope: %i[name province]}
    has_many :offices
end

app/models/office.rb
class Office < ApplicationRecord
    validates :name, presence: true
    validates :name, uniqueness: true
    validates :address, presence: true
    validates :phone, presence: true
    belongs_to :locality
    has_many :schedules, dependent: :destroy
    accepts_nested_attributes_for :schedules, allow_destroy: true
    
end

app/models/schedule.rb
class Schedule < ApplicationRecord
    validates :day, presence: true
    validates :start_time, presence: true
    validates :end_time, presence: true
    belongs_to :office
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
    validates :username, uniqueness: true
    validates :username, presence: true
    validates :role, presence: true
    validates :password, presence: true, if: -> { new_record? || changes[:crypted_password] }
    has_many :appointments
    
    enum role:{
        admin: 0,
        employee: 1,
        client: 2
    }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/appointments_controller.rb
class AppointmentsController < CrudController
  
    private 
    def model_params
      params.require(:appointment).permit(:datetime, :motive, :client, :employee, :office)
    end
  
    def get_model
      Appointment
    end
  
    def model_name
      "appointment"
    end

    def get_client
        User.find(model_params[:client])
        end
    
    def get_employee
        User.find(model_params[:employee])
    end

    def get_office
        Office.find(model_params[:office])
    end
  end
  

app/controllers/crud_controller.rb
class CrudController < ApplicationController
  before_action :set_model, only: %i[ show edit update destroy ]

  def index
    @model = get_model.all
  end

  def new
    @model = get_model.new
  end

  def edit; end

  def show; end

  def create
    @model = get_model.new(model_params)

    if @model.save
      redirect_to @model, notice: "#{model_name} was successfully created"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @model.update(model_params)
      redirect_to @model, notice: "#{model_name} was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @model.destroy

    redirect_to get_model
  end

  private 

  def set_model
    @model = get_model.find(params[:id])
  end

  def get_model
    raise NotImplementedError
  end

end

app/controllers/localities_controller.rb
class LocalitiesController < CrudController

  private 

  def model_params
    params.require(:locality).permit(:name, :province)
  end

  def get_model
      Locality
  end

  def model_name
    "locality"
  end
end

app/controllers/offices_controller.rb
class OfficesController < CrudController
    def create 
      
        @model = Office.new(name: model_params[:name], address: model_params[:address], phone: model_params[:phone], locality: get_locality, schedules_attributes: model_params[:schedules_attributes])
        if @model.save 
          redirect_to @model, notice: "#{model_name} was successfully created"
        else
          render :new, status: :unprocessable_entity
        end
    end

    def update
      if @model.update(name: model_params[:name], address: model_params[:address], phone: model_params[:phone], locality: get_locality, schedules_attributes:  model_params[:schedules_attributes] )
        redirect_to @model, notice: "#{model_name} was successfully updated."
      else
          render :edit, status: :unprocessable_entity
      end
    end
    
    private 
    def model_params
      params.require(:office).permit(:name, :address, :phone, :locality, schedules_attributes: [ :day, :start_time, :end_time, :_destroy])
    end
  
    def get_model
        Office
    end
  
    def model_name
      "Office"
    end

    def get_locality
      Locality.find(model_params[:locality])
    end

    def get_available_appointments
      @model.appointments.where(motive: "Available")
    end

    def create_appointments
      s = @model.schedule
      s.each do |day|
        hours = day.end_time - day.start_time
        quantity.to_i = hours / 15
        quantity.to_i.times do |i|
          Appointment.create(datetime: day.start_time + i*15.minutes, motive: "Available", office: @model)
        end
      end
    end

    

    def get_taken_appointments
      @model.appointments.where.not(motive: "Available")
    end
    
  end
  

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    byebug
    @user = login(params[:username], params[:password])

    if @user
      redirect_back_or_to(:users, notice: 'Login successful')
    else
      flash.now[:alert] = 'Login failed'
      render action: 'new', status: :unprocessable_entity 
    end
  end

  def destroy
    logout
    redirect_to(:users, notice: 'Logged out!')
  end
end

app/controllers/users_controller.rb
class UsersController < CrudController
  
  private 
  def model_params
    params.require(:user).permit(:username, :role, :password)
  end

  def get_model
    User
  end

  def model_name
    "user"
  end

  def get_clients
    @model = User.all
    clients = @model.collect { |user| [user.role==1] }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
def provinces_for_select
    [
        ["Buenos Aires", "Buenos Aires"],
        ["Catamarca", "Catamarca"],
        ["Chaco", "Chaco"],
        ["Chubut", "Chubut"],
        ["Corrientes", "Corrientes"],
        ["Córdoba", "Córdoba"],
        ["Entre Ríos", "Entre Ríos"],
        ["Formosa", "Formosa"],
        ["Jujuy", "Jujuy"],
        ["La Pampa", "La Pampa"],
        ["La Rioja", "La Rioja"],
        ["Mendoza", "Mendoza"],
        ["Misiones", "Misiones"],
        ["Neuquén", "Neuquén"],
        ["Río Negro", "Río Negro"],
        ["Salta", "Salta"],
        ["San Juan", "San Juan"],
        ["San Luis", "San Luis"],
        ["Santa Cruz", "Santa Cruz"],
        ["Santa Fe", "Santa Fe"],
        ["Santiago del Estero", "Santiago del Estero"],
        ["Tierra del Fuego", "Tierra del Fuego"],
        ["Tucumán", "Tucumán"]
    ]
    end

    def days_for_select
        [
            ["Lunes", "Lunes"],
            ["Martes", "Martes"],
            ["Miércoles", "Miércoles"],
            ["Jueves", "Jueves"],
            ["Viernes", "Viernes"],
        ]
    end
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/appointments/_form.html.erb
<%= form_with(model: appointment) do |form| %>
  <% if appointment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
        <% appointment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :office, style: "display: block" %>
    <%= form.select(:office,options_for_select(Office.all.map{|office| [office.name,office.id, office.get_available_appointments]})) %>
    <%= form.select(:office,options_for_select(Office.get_available_appointments)) %> 
  </div>

  <div>
    <%= form.label :motive, style: "display: block" %>
    <%= form.text_field :motive %>
  </div>

  <div>
    <%= form.label :date, style: "display: block" %>
    <%= form.datetime_select :date %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/appointments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Appointments</h1>

<div id="appointments">
  <% @model.each do |appointment| %>
    <%= render appointment %>
    <p>
      <%= link_to "Show this appointment", appointment %>
    </p>
  <% end %>
</div>

<%= link_to "New appointment", new_appointment_path %>

app/views/appointments/new.html.erb
<h1> New appointment </h1>

<%= render "form", appointment: @model %>

<div>
<%= link_to "Back to appointments", appointments_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TPIBanco</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>  
    <%= render "/navbar" %>
    <div id="nav">
    <% if current_user %>
      <%= link_to "Edit Profile", edit_user_path(current_user.id) %>
      <%= link_to "Logout", :logout, method: :post %>
    <% else %>
      <%= link_to "Register", new_user_path %> |
      <%= link_to "Login", :login %>
    <% end %>
  </div>
    <%= yield %>
  </body>
</html>

app/views/localities/_form.html.erb
<%= form_with(model: locality) do |form| %>
  <% if locality.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(locality.errors.count, "error") %> prohibited this locality from being saved:</h2>

      <ul>
        <% locality.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
   <%= form.label :province %>
   <%= form.select(:province,options_for_select(provinces_for_select)) %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/localities/_locality.html.erb
<div id="<%= dom_id locality %>">
  <p>
    <strong>Name:</strong>
    <%= locality.name %>
  </p>

  <p>
    <strong>Province:</strong>
    <%= locality.province %>
  </p>

</div>

app/views/localities/edit.html.erb
<h1>Editing locality</h1>

<%= render "form", locality: @model %>

<br>

<div>
  <%= link_to "Show this locality", @model %> |
  <%= link_to "Back to localities", localities_path %>
</div>

app/views/localities/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Localities</h1>

<div id="localities">
  <% @model.each do |locality| %>
    <%= render locality %>
    <p>
      <%= link_to "Show this locality", locality %>
    </p>
  <% end %>
</div>

<%= link_to "New locality", new_locality_path %>

app/views/localities/new.html.erb
<h1> New locality </h1>

<%= render "form", locality: @model %>

<div>
<%= link_to "Back to localities", localities_path %>
</div>

app/views/localities/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @model %>

<div>
  <%= link_to "Edit this locality", edit_locality_path(@model) %> |
  <%= link_to "Back to localities", localities_path %>

  <%= button_to "Destroy this locality", @model, method: :delete %>
</div>

app/views/offices/_form.html.erb
<%= form_with(model: office) do |form| %>
  <% if office.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(office.errors.count, "error") %> prohibited this office from being saved:</h2>

      <ul>
        <% office.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :address, style: "display: block" %>
    <%= form.text_field :address %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone %>
  </div>

  <div>
    <%= form.label :locality %>
    <%= form.select(:locality,options_for_select(Locality.all.map{|locality| [locality.name,locality.id]})) %>
  </div>

  <div data-controller="schedule">
    <template data-schedule-target="scheduleTemplate">       
          <%=form.fields_for :schedules, Schedule.new,  child_index: "TEMPLATE_RECORD" do |schedule| %>
            <%= render "schedule_fields", form: schedule %>
          <% end %>
    </template>

    <fieldset data-schedule-target="schedules"> 
      <legend>Schedule</legend>
    </fieldset>

    <%= link_to "Add schedule", "#", data: {action: "schedule#addSchedule"} %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/offices/_office.html.erb
<div id="<%= dom_id office %>">
  <p>
    <strong>Name:</strong>
    <%= office.name %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= office.address %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= office.phone %>
  </p>

  <p>
    <strong>Locality:</strong>
    <%= office.locality.name %>
  </p>

  <p>
    <strong>Schedule:</strong>
    
    <% office.schedules.map do |s| %>
      <div>
      <%= s.day %>: <%= s.start_time.strftime("%H:%M") %> - <%= s.end_time.strftime("%H:%M") %>
      </div>
    <% end %>
  </p>

</div>

app/views/offices/_schedule_fields.html.erb
<div class="nested-fields">
<div class="form-group">
    <%= form.hidden_field :_destroy %>
    <%= form.label :day %>
    <%= form.select(:day, days_for_select)%>
    <%= form.label :start_time %>
    <%= form.time_field :start_time%>
    <%= form.label :end_time %>
    <%= form.time_field :end_time%>
    <%= link_to "Remove", "#", data: {action: "click->schedule#removeSchedule"} %>
</div>
</div>

app/views/offices/edit.html.erb
<h1>Editing office</h1>

<%= render "form", office: @model %>

<br>

<div>
  <%= link_to "Show this office", @model %> |
  <%= link_to "Back to offices", offices_path %>
</div>

app/views/offices/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Offices</h1>

<div id="offices">
  <% @model.each do |office| %>
    <%= render office %>
    <p>
      <%= link_to "Show this office", office %>
    </p>
  <% end %>
</div>

<%= link_to "New office", new_office_path %>

app/views/offices/new.html.erb
<h1> New office </h1>

<%= render "form", office: @model %>

<div>
<%= link_to "Back to offices", offices_path %>
</div>

app/views/offices/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @model %>

<div>
  <%= link_to "Edit this office", edit_office_path(@model) %> |
  <%= link_to "Back to offices", offices_path %>

  <%= button_to "Destroy this office", @model, method: :delete %>
</div>

app/views/user_sessions/_form.html.erb
<%= form_with url: login_path, method: :post do |f| %>
  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="actions">
    <%= f.submit "Login" %>
  </div>
<% end %>

app/views/user_sessions/create.html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

app/views/user_sessions/destroy.html.erb
<h1>UserSessions#destroy</h1>
<p>Find me in app/views/user_sessions/destroy.html.erb</p>

app/views/user_sessions/new.html.erb
<h1>Login</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :username, style: "display: block" %>
    <%= form.text_field :username %>
  </div>

  <div>
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div>
   <%= form.label :role %>
   <%= select_tag(:role,options_for_select(User.roles)) %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Username:</strong>
    <%= user.username %>
  </p>

  <p>
    <strong>Role:</strong>
    <%= user.role %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render "form", user: @model %>

<br>

<div>
  <%= link_to "Show this user", @model %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @model.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New User", new_user_path %>

app/views/users/new.html.erb
<h1> New User </h1>

<%= render "form", user: @model %>

<div>
<%= link_to "Back to Users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @model %>

<div>
  <%= link_to "Edit this user", edit_user_path(@model) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @model, method: :delete %>
</div>